# Dùng Node.js LTS
FROM node:22-alpine

# Tạo thư mục làm việc trong container
WORKDIR /app

# Copy package.json trước để tận dụng cache
COPY package*.json ./

# Cài dependencies
RUN npm install

# Copy toàn bộ source code
COPY . .

# Expose port app đang chạy (đổi nếu khác)
EXPOSE 5001

# Lệnh khởi động
CMD ["npm", "start"]